name: cups-pdf

services:
  cups-pdf-cups:
    image: cups
    container_name: cups-pdf-cups
    volumes:
      - ${HOST_DATA_VOLUME}:/data
    build:
      args:
        ROOT_PASSWD: ${ROOT_PASSWD}
    networks:
      cups-ipvlan:
        ipv4_address: ${APP_PRINTER_IP}
      cups-bridge:

networks:
  cups-bridge:
    driver: bridge
  cups-ipvlan:
    driver: ipvlan
    ipam:
      config:
        - subnet: ${APP_SUBNET}
          gateway: ${APP_GATEWAY}
    driver_opts:
      parent: ${APP_NIC}